# Generated by Django 2.1.5 on 2019-08-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='terminado',
            field=models.BooleanField(default=True),
        ),
    ]
